fixed missing argument in header
Fixed TypeError: Header() missing 1 required positional argument: 'default'
Added request as paramerer in read_items so that Headers can be read and processed