Updated fix for mypy lint error
Re-did the lint fix for

    fastapi/dependencies/utils.py:50: error: Module "pydantic.typing" does not explicitly
    export attribute "ForwardRef"; implicit reexport disabled

so that it also passes the 3.6 and 3.7 CI pipelines.