Add default to Path parameter
If the `default` argument to `Path` is omitted, a TypeError is raised

```python
TypeError: Path() missing 1 required positional argument: 'default'
```